product_type = 'connect_cloud'
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'html'
entrypoint = 'analysis.html'
source = 'analysis.qmd'
validate = true
files = [
  '/analysis.html',
  '/.posit/publish/An Application of Location Quo-DPL8.toml',
  '/.posit/publish/deployments/deployment-Q6HA.toml'
]
title = 'An Application of Location Quotients to High-Impact Offenses'
